# Server configuration
server:
  port: 8080

spring:
  servlet:
    multipart:
      # 设置单个文件的最大大小为 10GB
      max-file-size: 10GB
      # 设置整个请求的最大大小为 10GB
      max-request-size: 10GB

# Group configuration
pasteboard:
  groups:
    - name: 普通用户组
      directory: /opt/pasteboard/data2
      users:
        - username: user1
          password: pass1
          role: user
    - name: 管理员组
      directory: /opt/pasteboard/data
      users:
        - username: admin
          password: admin123
          role: admin