# Server configuration
server:
  port: 8080

spring:
  servlet:
    multipart:
      # 设置单个文件的最大大小为 10GB
      max-file-size: 10GB
      # 设置整个请求的最大大小为 10GB
      max-request-size: 10GB

# Group configuration
pasteboard:
  groups:
    - name: default
      directory: /opt/pasteboard/data
      users:
        - username: user1
          password: pass1
          role: user
    - name: admin_group
      directory: /opt/pasteboard/data
      users:
        - username: admin
          password: admin123
          role: admin